{"name": "test_add[无效用例]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 7", "trace": "self = <pytest_practice1.test_calculator.TestCalculator object at 0x000001818EDF2F98>\nget_calculator = <pytest_practice1.calculatorCode.calculator.Calculator object at 0x000001818EDF25C0>, a = 3, b = 4, expect = 5, get_calculator1 = None\n\n    @pytest.mark.first\n    @allure.story(\"测试加法计算功能\")\n    @pytest.mark.parametrize(\"a,b,expect\",get_datas()[0],ids=get_datas()[1])  # 参数化 , ids命名测试用例结果\n    def test_add(self,get_calculator,a,b,expect,get_calculator1):\n        print(\"测试相加\")\n        result = round(get_calculator.add(a,b),2)\n>       assert expect == result\nE       assert 5 == 7\n\ntest_calculator.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "2bcda449-c6a1-44ac-832d-09683be08749-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "4"}, {"name": "expect", "value": "5"}], "start": 1598277999421, "stop": 1598277999423, "uuid": "51712a33-fa26-4763-99ad-b88c55e03334", "historyId": "0b0c6b82d971bdf3cae89f39c9ff9e26", "testCaseId": "c0380ad0f93ea623c2328a25b0918ec2", "fullName": "test_calculator.TestCalculator#test_add", "labels": [{"name": "feature", "value": "计算器功能测试"}, {"name": "story", "value": "测试加法计算功能"}, {"name": "tag", "value": "first"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-O9I37L5"}, {"name": "thread", "value": "8716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}